USE [master];
GO

CREATE DATABASE [PingMe]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'WhatsApp', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.KALANJIYAM\MSSQL\DATA\WhatsApp.mdf' , SIZE = 5120KB , FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'WhatsApp_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL11.KALANJIYAM\MSSQL\DATA\WhatsApp_log.ldf' , SIZE = 1024KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [PingMe] SET COMPATIBILITY_LEVEL = 100
GO
ALTER DATABASE [PingMe] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [PingMe] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [PingMe] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [PingMe] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [PingMe] SET ARITHABORT OFF 
GO
ALTER DATABASE [PingMe] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [PingMe] SET AUTO_CREATE_STATISTICS ON 
GO
ALTER DATABASE [PingMe] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [PingMe] SET AUTO_UPDATE_STATISTICS OFF 
GO
ALTER DATABASE [PingMe] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [PingMe] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [PingMe] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [PingMe] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [PingMe] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [PingMe] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [PingMe] SET  DISABLE_BROKER 
GO
ALTER DATABASE [PingMe] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [PingMe] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [PingMe] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [PingMe] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [PingMe] SET  READ_WRITE 
GO
ALTER DATABASE [PingMe] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [PingMe] SET  MULTI_USER 
GO
ALTER DATABASE [PingMe] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [PingMe] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
USE [PingMe]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [PingMe] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
